name: tailscale

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Tailscale Action
        uses: ./
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: check for hello.ipn.dev in netmap
        run:
          tailscale status | grep -q hello
